### PR TITLE
TF-898 Quick creating rule in email detailed view

### PR DESCRIPTION
**Pull request by dab246**
#898 

### Resolved

https://user-images.githubusercontent.com/80730648/201263929-8fa9bc2d-9852-46f4-97e4-e046f0e58b87.mov

https://user-images.githubusercontent.com/80730648/201272302-4c867acb-0d53-402b-b294-8b7c3d678fba.mov

### CODE REVIEW

**Review by ManhNTX — APPROVED** [review]

**Comment by chibenwa** [comment]
Cool!

When i click on the email address the message should rather be `create a rule for this sender` imo

**Comment by hoangdat** [comment]
> When i click on the email address the message should rather be `create a rule for this sender` imo

Hi @chibenwa, We need the feedback, but you as the expert of email as well as the PO, please do the review for the UI in Figma, before we implement it. It makes less effort for us and save the rework time

**Review by hoangdat — APPROVED** [review]

**Comment by chibenwa** [comment]
@hoangdat for design, UX, I review what I get presented on mondays ;-)

Otherwise I also review things I am tagged on in github.

I must confess dismissing the rest ;-)

**Comment by chibenwa** [comment]
BTW I just asked changing a text field ;-) 

Tiny tiny tiny suggestion ^^

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
