### PR TITLE
 #605 Download attachment in OIDC

### PR DESCRIPTION
**Pull request by dab246**

### CODE REVIEW

**Comment by hoangdat** [comment]
please squash all unrelated commits into 1 commits with the message `[DO NOT REVIEW] bla bla`.
- we are easily to focus to review the main problem
- we are easily to manage the commit's history when `fixup`, `rebase`, ...

**Comment by hoangdat** [comment]
we have the problem with CICD at the moment, I am trying to fix it. Update soon.

**Comment by dab246** [comment]
> please squash all unrelated commits into 1 commits with the message `[DO NOT REVIEW] bla bla`.
> 
> * we are easily to focus to review the main problem
> * we are easily to manage the commit's history when `fixup`, `rebase`, ...

You should not review this PR. I marked it as [WIP] so it's not official PR to review yet

**Comment by chibenwa** [comment]
How about upload? Still working?

**Comment by hoangdat** [comment]
> How about upload? Still working?

No problem, not impact to upload.

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
