### PR TITLE
TF-904 Clicking mailbox name redirects to mailbox

### PR DESCRIPTION
**Pull request by alagane**
Related issue #904

When clicking on the line with the mailbox name, it goes back to the mailbox.
The link "size" is very wide, until the "move message" button, so licking on the "white space" also redirects to mailbox, but I don't think it is a problem.
Feel free to test or suggest changes.

### CODE REVIEW

**Review by hoangdat — COMMENTED** [review]
IMO, it is better if `back` and `mailbox's name` are both children of an `InkWell`? WDYT?

**Comment by hoangdat** [comment]
build failed

image

need more investigate from teamMail team

**Comment by alagane** [comment]
> IMO, it is better if `back` and `mailbox's name` are both children of an `InkWell`? WDYT?

Might be a good idea, though the back button has some effect on mouseover (more like a button), and putting them both children of an InkWell might remove this effect.

**Comment by dab246** [comment]
@alagane @hoangdat  I fixed it. How do you feel? Please see the demo video below.
-  Web:


https://user-images.githubusercontent.com/80730648/188419278-edb29d6e-f490-47bf-bd77-3c3059ad9020.mov


- Mobile: 

https://user-images.githubusercontent.com/80730648/188419388-118eba11-4e50-468e-b38f-877ec0127297.mov

**Review by ManhNTX — APPROVED** [review]

**Comment by hoangdat** [comment]
Hi @dab246 overall are good. But IMO, it should be better if our `ripple` (red marked below) have round corner 

Screen Shot 2022-09-05 at 17 06 12

**Comment by dab246** [comment]
> Hi @dab246 overall are good. But IMO, it should be better if our `ripple` (red marked below) have round corner
> 
> Screen Shot 2022-09-05 at 17 06 12

@hoangdat Oke. I updated it. Please see below image:
Screen Shot 2022-09-05 at 18 06 17

**Comment by alagane** [comment]
Way better than my version, good work :)

**Pull request merged**
