### PR TITLE
[TRANSLATION] Add `Arabic, Italian` support

### PR DESCRIPTION
**Pull request by dab246**
### Issues
- #1579 
- #1580 
- #1581 

### Resolved

https://user-images.githubusercontent.com/80730648/224311679-84d5ca1f-210c-4e23-868b-841069b34c7f.mov

### CODE REVIEW

**Review by nqhhdev — APPROVED** [review]

**Comment by chibenwa** [comment]
Screenshot from 2023-03-10 21-15-43

A few untranslated strings for vietnamese?

**Comment by hoangdat** [comment]
If you want to release include these translation, please go to weblate to make request to l10n branch, then make PR to master from l10n.

**Comment by chibenwa** [comment]
> If you want to release include these translation, please go to weblate to make request to l10n branch, then make PR to master from l10n.

Pro-tip: don't ask to your boss to do Vietnamese translation himself while he speaks a broken vietnamese: you won't win that!

@dieptran88 you are in charge to enforce full translations nheeee

**Comment by hoangdat** [comment]
> > If you want to release include these translation, please go to weblate to make request to l10n branch, then make PR to master from l10n.
> 
> 
> 
> Pro-tip: don't ask to your boss to do Vietnamese translation himself while he speaks a broken vietnamese: you won't win that!
> 
> 
> 
> @dieptran88 you are in charge to enforce full translations nheeee

Dat Vu's mean about the process of weblate. He has not permission. Let's me check.

**Comment by hoangdat** [comment]
> > If you want to release include these translation, please go to weblate to make request to l10n branch, then make PR to master from l10n.
> 
> 
> 
> Pro-tip: don't ask to your boss to do Vietnamese translation himself while he speaks a broken vietnamese: you won't win that!

Dat Vu's mean about the process of weblate. He has not permission. Let's me check.

**Pull request merged**
