### PR TITLE
TF-1155 Change input suggestion field  for fields "From"/"To" in advance search

### PR DESCRIPTION
**Pull request by hieutbui**
## Issue
---
#1155 

## Resolved
---
https://github.com/linagora/tmail-flutter/assets/80142234/1d532f64-fa44-4579-9092-e0a82a2e4478

### CODE REVIEW

**Comment by hoangdat** [comment]
- IMO, we need to apply the same behavior with `to` in composer

**Comment by hoangdat** [comment]
@dab246 

### Blocking
- When open advance search 2nd time and click on 'From/To', UI not breaking but got error about _onFocusChange() function inside lib super_tag_editor.
- When 'From' is on focus then press Tab => focus switch to 'To' and then disappear.
- When 'To' is on focus then press Tab => focus disappear.
- When focus is on 'From/To' then click on other fields, this 'From/To' will not collapse.

**Comment by dab246** [comment]
## Resolved


https://github.com/linagora/tmail-flutter/assets/80730648/115781e4-a4bc-4e21-a3dc-be28ea1caf95



@hoangdat  @hieutbui  Please review it

**Comment by hieutbui** [comment]
I tested and it works as expected

**Review by dab246 — APPROVED** [review]
lgtm

**Review by nqhhdev — APPROVED** [review]

**Pull request merged**
