### PR TITLE
TF-256 Change login form for web

### PR DESCRIPTION
**Pull request by dab246**
- [x] User don't need to input URL
- [x] Use environment variable to provide the JMAP server URL.
- [x] Setup web in docker

Screen Shot 2022-02-18 at 15 30 34

### CODE REVIEW

**Comment by chibenwa** [comment]
Wow

 -> What's the name for the ENV variable of the URL
 -> Can we publish this image somewhere?
 -> Can we have a bit of doc (eg in README) on how to launch the docker image?
 
 @hoangdat we also need to push the docker image as part of the build process to dockerhub linagora account, tag `branch-master`. Maybe you can see with @tnstung how/when to do that?

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project-private/issues/348 FYI for the work the backend will do on the TMail SPA

**Comment by hoangdat** [comment]
> Wow
> 
> -> What's the name for the ENV variable of the URL -> Can we publish this image somewhere? -> Can we have a bit of doc (eg in README) on how to launch the docker image?
> 
> @hoangdat we also need to push the docker image as part of the build process to dockerhub linagora account, tag `branch-master`. Maybe you can see with @tnstung how/when to do that?

yes, a lot interesting question for us, we are investigating. Hope we have it soon. I created some tịcket to handle it step by step. #273 #274. all of these are new for us. Please be patient and share any things relate to us :)

**Comment by hoangdat** [comment]
> linagora/james-project-private#348

what SPA? and can you explain a bit about what are you doing? (srr for this kind of question. we are noob on web :))

**Comment by chibenwa** [comment]
(We will help as much as we can)

**Comment by hoangdat** [comment]
> SPA -> Single Page application, like INBOX SPA, calendar SPA
> 
> That is for the vocabulary.
> 
> What the java team will do is:
> 
> * How much static assets are pulled by the browser. A good quality web app requires low data transfer
> * With a web app we can easily audit the JMAP calls
> * We will test how good the docker package mentionned above is (performance tests)
> * We then will industrialise the deployments using Kubernetes and Helm packaging
> * We will deploy it on pre-production
> * We will deploy in on tmail.linagora.com/beta and have same dâta than openpaas.linaagora.com
> 
> Clearly we can share the work with your team.
> 
> You want me to ỏrganise a meeting monday morning about thís?

no need for the meeting next week, maybe the week after. We need to warm the work up :)

**Comment by Arsnael** [comment]
For the docker part if you need help don't hesitate too. People in the backend team have the skills regarding this :)

**Comment by hoangdat** [comment]
> For the docker part if you need help don't hesitate too. People in the backend team have the skills regarding this :)

yes, please take a look on it, then help us. @Arsnael

**Pull request merged**
