### PR TITLE
Hot fix some bug UI

### PR DESCRIPTION
**Pull request by dab246**
## Issue

- [x] Alignment receive time in email view
- [x] Excess space when subject is empty
- [x] The `platformViewRegistry` in `dart:ui` is deprecated

## Resolved

- Alignment receive time in email view:

<table>
 <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

- Excess space when subject is empty:

<table>
 <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>subject -old</td>
    <td>Screenshot 2024-06-27 at 10 51 57</td>
  </tr>
</table>

https://github.com/linagora/tmail-flutter/assets/80730648/49c0d90c-63ab-4a80-abbd-e67e1799eb71

### CODE REVIEW

**Comment by tddang-linagora** [comment]
- [ ] Test focus transitioning when pressing `Tab` on keyboard (Due to code change in relevant functionality)

**Review by tddang-linagora — APPROVED** [review]

**Comment by dab246** [comment]
Rebased. Please review again @hoangdat

**Comment by hoangdat** [comment]
Please add a small issue:
- [ ] remove blink blink of `next - previous` button in Email View

**Comment by dab246** [comment]
> Please add a small issue:
> 
> * [ ]  remove blink blink of `next - previous` button in Email View

Please attach a demo video to it.

**Comment by hoangdat** [comment]
- [ ] hyperlink iOS still show full link
Screenshot 2024-09-23 at 10 44 18

**Comment by dab246** [comment]
> Please add a small issue:
> 
> * [x]  remove blink blink of `next - previous` button in Email View

Fixed.

https://github.com/user-attachments/assets/bc49ddb5-a62a-4c84-b5c8-4bbab992b354

**Comment by dab246** [comment]
> * [x]  hyperlink iOS still show full link
> 
> Screenshot 2024-09-23 at 10 44 18

Fixed.

https://github.com/user-attachments/assets/53f5ccb3-acf7-4654-b473-ef6a96e5e888

**Review by tddang-linagora — APPROVED** [review]

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
