### PR TITLE
Migrate `v0.11.3-patch4-dev` to `master` branch

### PR DESCRIPTION
**Pull request by dab246**
- Display warning dialog when `pick/drag&drop/share` attachment/inline in composer
- Show sending dialog when `send/save` email
- Selectable in blue bar
- Add button `Mail to attendees`  to  open composer with to all attendees
- Improve composer UI
- Signature
- Communicating I18n to remote servers

## Blocker

- Need merged: https://github.com/linagora/jmap-dart-client/pull/87

### CODE REVIEW

**Comment by tddang-linagora** [comment]
@tddang-linagora Test iOS

- [ ] Display warning dialog when pick/drag&drop/share attachment/inline in composer
- [ ] Show sending dialog when send/save email
- [ ] Selectable in blue bar
- [ ] Add button Mail to attendees to open composer with to all attendees
- [ ] Improve composer UI
- [ ] Signature
- [ ] Communicating I18n to remote servers

**Comment by tddang-linagora** [comment]
Composer inline image with >10mb doesn't have warning dialog

https://github.com/linagora/tmail-flutter/assets/160106668/5270aad9-cbe3-4fc3-8965-7c522606dc9a

**Comment by dab246** [comment]
> Composer inline image with >10mb doesn't have warning dialog
> 
>  composer-inline-10mb.mov

Dialog warning about files  `>10 MB` only checks for `attachment`, not `inline image`

**Comment by hoangdat** [comment]
- [ ] @tddang-linagora please help me verify memory-leak for this changes. Thank you

**Comment by hoangdat** [comment]
- [ ] can not reply event successfully in iOS (yes/no/maybe)

**Comment by dab246** [comment]
> * [ ]  can not reply event successfully in iOS (yes/no/maybe)

Checked that it was a server error when making `CalendarEvent` requests

Screenshot 2024-06-07 at 12 50 56

**Comment by tddang-linagora** [comment]
> * [x]  @tddang-linagora please help me verify memory-leak for this changes. Thank you

Pick inline image OK
Screenshot 2024-06-10 at 09 14 24

**Comment by tddang-linagora** [comment]
@dab246  Drag & drop image bug


https://github.com/linagora/tmail-flutter/assets/160106668/0bee1784-495d-4b39-89cb-0a1995c2b4bb

**Comment by tddang-linagora** [comment]
> * [x]  @tddang-linagora please help me verify memory-leak for this changes. Thank you

Pick attachment memory leak
Screenshot 2024-06-10 at 09 36 40

**Comment by tddang-linagora** [comment]
> * [x]  @tddang-linagora please help me verify memory-leak for this changes. Thank you

View heavy email OK
Screenshot 2024-06-10 at 09 46 35

**Comment by hoangdat** [comment]
- [ ] create a separate branch from this branch with Firebase analytics to verify other problem

**Pull request merged**
