### PR TITLE
TF-#84 Add icon and splash screen for Android in early release 

### PR DESCRIPTION
**Pull request by hoangdat**
#84

Screenshot_20210915-204155
Screenshot_20210915-204212

### CODE REVIEW

**Comment by chibenwa** [comment]
No PNG.... Upload did not finish?

**Comment by hoangdat** [comment]
> No PNG.... Upload did not finish?

hard to upload to github yesterday

**Review by dab246 — COMMENTED** [review]
Too bad. I think you should redesign and then finish this PR.

**Comment by hoangdat** [comment]
> Too bad. I think you should redesign and then finish this PR.

No, we will update it whenever we have designer, this PR to update the app with at least for detection in some test release.

**Comment by chibenwa** [comment]
Once we are at it TMail -> Team-Mail

**Review by dab246 — APPROVED** [review]

**Pull request merged**
