### PR TITLE
TF-3171 Fix duplicate signature button on Composer view changed

### PR DESCRIPTION
**Pull request by tddang-linagora**
## Issue
- #3171 

# Demo

https://github.com/user-attachments/assets/86e9c79a-1a58-4ff1-bd39-d90685d0616c

### CODE REVIEW

**Comment by dab246** [comment]
- [ ] Cannot change content signature when switch full screen ↔ normal screen  ↔ minimize screen


https://github.com/user-attachments/assets/3821e404-d06a-4210-842c-539ff6233367

**Comment by tddang-linagora** [comment]
>Cannot change content signature when switch full screen ↔ normal screen ↔ minimize screen


https://github.com/user-attachments/assets/362d802a-3982-4ea3-bd40-6cdddc291c2f

**Review by dab246 — APPROVED** [review]
- [ ] rebase

**Comment by dab246** [comment]
Moved to https://github.com/linagora/tmail-flutter/pull/3184

**Pull request closed without merging**
