### PR TITLE
#339 Fix Empty item on ThreadView

### PR DESCRIPTION
**Pull request by hoangdat**

### CODE REVIEW

**Comment by chibenwa** [comment]
> Clean up the cache whenever start the app

This I imagine can be debatable. I am not that sure about it, but I let you choose.

**Comment by hoangdat** [comment]
> > Clean up the cache whenever start the app
> 
> This I imagine can be debatable. I am not that sure about it, but I let you choose.

FYI, 
- before: we delete all the item in the cache have `received at` more than 30 days from before today, it means that, the first time user START the app today, we will execute clean up.

- now: we delete all the items in the cache have `received at` more than 10 days from now, it means that, every time which the user START the app, we will execute clean up

START = app is terminated before, not in the stack of multitask on mobile, and it is different with app run in background.

**Review by dab246 — APPROVED** [review]
LGTM.

**Review by johnnguyenit39 — COMMENTED** [review]
read it

**Pull request merged**
