### PR TITLE
TF-1417 Remove Plain/Text when create signature

### PR DESCRIPTION
**Pull request by nqhhdev**
#1417 , #1467 , #1476 

- Remove Plain/Text when create signature

### Demo 

`MOBILE`

https://user-images.githubusercontent.com/99852347/220156619-e7fdd643-0f4d-4862-a397-58aa2e2688f3.mp4

`WEB`

https://user-images.githubusercontent.com/99852347/220156750-a04275ac-0cd0-497a-9fcf-91ae9f4fe29e.mov

### CODE REVIEW

**Comment by nqhhdev** [comment]
add Padding to `ToolbarRichTextWebBuilder`

https://user-images.githubusercontent.com/99852347/220155621-55f31d0d-d96d-485c-869a-aa4fe3762778.mov

**Comment by hoangdat** [comment]
for #1467, please demo the case:
```
user X is a member of team mailbox Y (teamY@domain.com),
user X want to create identity for the team mailbox with email (teamY@domain.xom)
```

**Comment by nqhhdev** [comment]
> for #1467, please demo the case:
> 
> ```
> user X is a member of team mailbox Y (teamY@domain.com),
> user X want to create identity for the team mailbox with email (teamY@domain.xom)
> ```

It will be moved to this ticket #1488

**Review by hoangdat — APPROVED** [review]

**Review by dab246 — APPROVED** [review]
lgtm

**Pull request merged**
