### PR TITLE
TF-1932 Turn off notifications after emailing

### PR DESCRIPTION
**Pull request by dab246**
### Issue

#1932 

### Resolved

https://github.com/linagora/tmail-flutter/assets/80730648/3fbf8aa3-e437-4088-8d3b-47a676eac8a0

### CODE REVIEW

**Comment by hoangdat** [comment]
@dieptran88 we need to show notification after sending queue item success or not?

**Comment by dieptran88** [comment]
> @dieptran88 we need to show notification after sending queue item success or not?

I think yes, we agreed to have the noti after sending queue successfully because it is not sent right after the user compose it, so need to inform user.

**Review by nqhhdev — APPROVED** [review]

**Comment by dieptran88** [comment]
> > @dieptran88 we need to show notification after sending queue item success or not?
> 
> I think yes, we agreed to have the noti after sending queue successfully because it is not sent right after the user compose it, so need to inform user.

Hi @dab246 @QuangHoang1210 @hoangdat , after comparing with other mail clients and get consulting from designer, we think sending notification in this case is not very necessary and may show too much notifications in a time if there are multiple emails in sending queue

**Comment by hoangdat** [comment]
Ok, totally agree with Diep about that. 
- No notification in Notification center of Android/iOS
- Only noti by toast inside app (only when app in foreground, sure).

How about it? @dab246 @QuangHoang1210

**Comment by dab246** [comment]
> 



> Ok, totally agree with Diep about that.
> 
> * No notification in Notification center of Android/iOS
> * Only noti by toast inside app (only when app in foreground, sure).
> 
> How about it? @dab246 @QuangHoang1210

If so, then I don't think it is necessary to notify in the app in the foreground because if there are many messages in the queue to send. We will have to display quite a few toasts at the same time. Re-rendering will cause flickering.

**Comment by QuangHoang1210** [comment]
Yeah. IMO we do not need to have notification this case.
The email was sent will be moved to Sent mailboxes.

The email is pending will be stay in sending queue. So no need to show notification for this one. User can check it by moving mailboxes from Sent -> Sending queue.

Note: We also have email sending status in Sending Queue.

**Comment by dab246** [comment]
@hoangdat We need to finalize a solution to this problem.

**Comment by hoangdat** [comment]
ok with Dat Vu, keep the error in the list of sending queue is enough, no need more for success case. Thanks

**Pull request merged**
