### PR TITLE
[BUG] Fix upload attachment

### PR DESCRIPTION
**Pull request by dab246**
https://user-images.githubusercontent.com/80730648/151537034-a2df591f-8523-4c27-abdb-dae265465bab.mov

### CODE REVIEW

**Comment by dab246** [comment]
@chibenwa @hoangdat  Please check the upload api again for me. The uploaded file cannot be opened. See details in the video below.

https://user-images.githubusercontent.com/80730648/150954727-d2340a92-412c-491b-a670-6091afed181f.mov

**Comment by chibenwa** [comment]
mmm Why are we having a Content/type jpeg on the response in the first place?

Uploads are not supposed to return the uploaded image but a short JSON with the blob id, and other information related to the uploaded blob.

**Comment by chibenwa** [comment]
cf https://github.com/apache/james-project/pull/862

**Comment by dab246** [comment]
> cf [apache/james-project#862](https://github.com/apache/james-project/pull/862)

@chibenwa Has this bug been fixed yet? I still can't do it successfully.

**Comment by chibenwa** [comment]
1. No it's in progress

2. If you just ignore the (wrong) content type and pretend it is JSON (which it is!) then there is no blocker at all!

**Comment by chibenwa** [comment]
Try to cat the response instead, to see the underlying JSON.

**Comment by dab246** [comment]
> Try to cat the response instead, to see the underlying JSON.

I tried, but the file size returned in json after successful upload and the actual uploaded file size is different.

**Comment by chibenwa** [comment]
Can you post the JSON result?

**Comment by dab246** [comment]
> Can you post the JSON result?

@chibenwa  Can you explain this to me?

````
{
  "accountId": "3ce33c876a726662c627746eb9537a1d13c2338193ef27bd051a3ce5c0fe5b12",
  "blobId": "uploads-4baffc90-7e79-11ec-ac27-732dd96cc126",
  "type": "image/jpeg",
  "size": 586388
}
````

https://user-images.githubusercontent.com/80730648/151120942-dba610a6-43e7-411f-8150-cdb76c77c2e1.mov

**Comment by chibenwa** [comment]
I'm having a look.

BTW @dab246 don't be impatient and take the time to clearly states your observations. You can structure your report in the following way: 1. what I observe 2. what I think is expected 3. useful complementary information. Just stating "your crap don't work, fix it" is not enough and thankfully people in the Quality Assurance area don't do that. It avoids other people not to guess, but jump straight to the diagnostic.

Can we agree on that?

Here is my take on your issue:

1. The size in the upload response do not match the size of the uploaded file
2. It should be the same
3. Pateform: OpenPaaS DEV

For yesterday 

1. The uploaded file is not returned in the upload response
2. It should 

We can agree that 2. is not spec compliant (and illogical) and that this confusion was caused by the content type of the response being mistakenly positionned to the content type of the uploaded object instead of JSON

Wich gives:

1. The upload response Content Type is of the type of the uploaded object
2. This should be application/json

And we have already a PR to fix that.

**Comment by dab246** [comment]
> I'm having a look.
> 
> BTW @dab246 don't be impatient and take the time to clearly states your observations. You can structure your report in the following way: 1. what I observe 2. what I think is expected 3. useful complementary information. Just stating "your crap don't work, fix it" is not enough and thankfully people in the Quality Assurance area don't do that. It avoids other people not to guess, but jump straight to the diagnostic.
> 
> Can we agree on that?
> 
> Here is my take on your issue:
> 
> 1. The size in the upload response do not match the size of the uploaded file
> 2. It should be the same
> 3. Pateform: OpenPaaS DEV
> 
> For yesterday
> 
> 1. The uploaded file is not returned in the upload response
> 2. It should
> 
> We can agree that 2. is not spec compliant (and illogical) and that this confusion was caused by the content type of the response being mistakenly positionned to the content type of the uploaded object instead of JSON
> 
> Wich gives:
> 
> 1. The upload response Content Type is of the type of the uploaded object
> 2. This should be application/json
> 
> And we have already a PR to fix that.

**1. Please send the PR link that you are fixing that error. I need to see.
2. The problem here I want to know is that the error is caused by the back-end side? I just need to know that.**

**Comment by chibenwa** [comment]
> 1. Please send the PR link that you are fixing that error. I need to see.

cf apache/james-project#862

(earlier in this discussion)

> 2. The problem here I want to know is that the error is caused by the back-end side? I just need to know that.

I'm investigating that since yesterday.

I don't succeed reproducing running James alone. If that's a James code issue I dont have enough details to reproduce it.

It *may* be a deployment issue. Like a NGinx cutting things in the middle. We shall continue to investigate.

**Comment by hoangdat** [comment]
@dab246 can you help Benoit to reproduce this issue.

(maybe the headers, content, ....)

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
