### PR TITLE
TF-2940 Add speller checker in more places

### PR DESCRIPTION
**Pull request by dab246**
## Issue

#2940 

## Resolved

- Speller check for Vacation/Identity/Subject input

https://github.com/user-attachments/assets/d64f6c49-ba74-45bc-b7b6-a6863fe36cfc

### CODE REVIEW

**Comment by dab246** [comment]
Rebase completed. Please review again @hoangdat

**Review by tddang-linagora — APPROVED** [review]

**Comment by hoangdat** [comment]
- [ ] when click in search folder in Mailbox View
image

**Comment by hoangdat** [comment]
- [ ] same for advanced search form, identity creator, ...

**Comment by dab246** [comment]
> * [x]  when click in search folder in Mailbox View. I run it in chrome dev mode (localhost) and maybe no extension.
> * [x]  same for advanced search form, identity creator, vacation, ....

Fixed. 


https://github.com/user-attachments/assets/ab6aa42d-fe09-4efe-9d1d-1a11e9ef86d7

**Review by tddang-linagora — APPROVED** [review]

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
