### PR TITLE
TF-2735 Gesture back for user in composer on mobile

### PR DESCRIPTION
**Pull request by dab246**
## Issue

#2735 

## Resolved

- Android 14:

https://github.com/linagora/tmail-flutter/assets/80730648/e9c9b1ca-cf01-4321-8253-144907fdf9e1

-iOS 17.2:

https://github.com/linagora/tmail-flutter/assets/80730648/e8039085-8eac-46c6-b8b0-4f5a811fcf6b

### CODE REVIEW

**Review by sherlockvn — APPROVED** [review]

**Review by tddang-linagora — APPROVED** [review]

**Comment by hoangdat** [comment]
- [ ] it did not work on Android 13

**Comment by hoangdat** [comment]
- [ ] how to prevent save to draft in case user open composer but not input anything

**Comment by dab246** [comment]
> * [ ]  how to prevent save to draft in case user open composer but not input anything

We have been handling this case for a long time. If you have a signature, it is considered that there is a change in content so the system will save the draft if you exit. If you do not have a signature, it will not automatically save

**Comment by dab246** [comment]
> * [ ]  it did not work on Android 13

Tested on android virtual machine and it works fine on Android 13. Please provide video proof if you get error on your device.

**Comment by hoangdat** [comment]
- Your android 33 still work, but I think it is Pixel and support `predictive back`, please test on device which don't have support of `predictive back`

**Comment by dab246** [comment]
> * Your android 33 still work, but I think it is Pixel and support `predictive back`, please test on device which don't have support of `predictive back`

If the device does not support `predictive back` then why can we let users use `swipe back`. They should use it like the old versions, which is to click the back button.

**Comment by dab246** [comment]
- [ ] Test swipe on Xiaomi 12

**Comment by dab246** [comment]
> * [x]  Support gesture back for devices don't have `predictive back`

1. Android 12 not supported `predictive back`:


[Android 12.webm](https://github.com/linagora/tmail-flutter/assets/80730648/9543551f-f1b3-45b5-b74e-88bcf0b825d2)



3. Android 13  supported `predictive back`:

[Android 13.webm](https://github.com/linagora/tmail-flutter/assets/80730648/ce5a7af7-65b1-4f00-8927-d4840c8f8361)

**Comment by dab246** [comment]
@hoangdat  Please review again

**Comment by dab246** [comment]
- [x] Disable gesture back for devices don't have `predictive back`

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
