### PR TITLE
TF-2323 Improve from filter in quick search result

### PR DESCRIPTION
**Pull request by hieutbui**
## Issues

#2323 
#2381 

## Demo

https://github.com/linagora/tmail-flutter/assets/80730648/a6a8c683-de79-4925-9785-04c27a104ff8

### CODE REVIEW

**Comment by dab246** [comment]
Also, please demo case search don't select people suggestion

**Comment by hieutbui** [comment]
> Also, please demo case
> 
> * [x]  search don't select people suggestion
> * [x]  Responsive mobile/tablet

I updated the demo video, please check it!

**Comment by hoangdat** [comment]
> The default when searching results should be fromMe

IMO, no need `from me` by default

**Comment by hoangdat** [comment]
### Note:
- [ ] if token no change, but time is expired, `current code` will register new one -> register will make the failed response -> again and again

**Review by dab246 — APPROVED** [review]

**Comment by dab246** [comment]
- [ ] Check #2381

**Comment by hieutbui** [comment]
@hoangdat About load more:
- Full request and response file: [load_more_sort.md](https://github.com/linagora/tmail-flutter/files/13576787/load_more_sort.md)
- Current load more with `subject` ascending and `beforOption` is `receiveAt` value of last item:
**Load more work with correct sort order**

https://github.com/linagora/tmail-flutter/assets/80142234/47fd9acd-6253-4711-8ad2-149578f38032


- Load more without beforeOption:
**Response always the same**


https://github.com/linagora/tmail-flutter/assets/80142234/225ae1da-6286-4d54-adac-9da556c11d69

**Comment by hoangdat** [comment]
Hi @chibenwa @Arsnael , we are trying to implement load more for sorting in search. 
is it correct when we base on the `receiveAt` to load more in this case: sort subject A -> Z
First request: 
```
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail",
        "urn:apache:james:params:jmap:mail:shares"
    ],
    "methodCalls": [
        [
            "Email/query",
            {
                "accountId": "3cd281b49cxxxxxxxxexx",
                "filter": {
                    "operator": "AND",
                    "conditions": [
                        {
                            "text": "firstname99"
                        }
                    ]
                },
                "sort": [
                    {
                        "isAscending": true,
                        "property": "subject"
                    }
                ],
                "limit": 20
            },
            "c0"
        ],
        [
            "Email/get",
            {
                "accountId": "3cd281b49cxxxxxxxxexx",
                "#ids": {
                    "resultOf": "c0",
                    "name": "Email/query",
                    "path": "/ids/*"
                },
                "properties": [
                    "id",
                    "subject",
                    "from",
                    "to",
                    "cc",
                    "bcc",
                    "keywords",
                    "size",
                    "receivedAt",
                    "sentAt",
                    "preview",
                    "hasAttachment",
                    "replyTo",
                    "mailboxIds",
                    "header:X-MEETING-UID:asText"
                ]
            },
            "c1"
        ]
    ]
}
```

and loadmore with request: 
```
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail",
        "urn:apache:james:params:jmap:mail:shares"
    ],
    "methodCalls": [
        [
            "Email/query",
            {
                "accountId": "3cd281b49cxxxxxxxxexx",
                "filter": {
                    "operator": "AND",
                    "conditions": [
                        {
                            "before": "2023-11-10T16:46:32.000Z",
                            "text": "firstname99"
                        }
                    ]
                },
                "sort": [
                    {
                        "isAscending": true,
                        "property": "subject"
                    }
                ],
                "limit": 20
            },
            "c0"
        ],
        [
            "Email/get",
            {
                "accountId": "3cd281b49cxxxxxxxxexx",
                "#ids": {
                    "resultOf": "c0",
                    "name": "Email/query",
                    "path": "/ids/*"
                },
                "properties": [
                    "id",
                    "subject",
                    "from",
                    "to",
                    "cc",
                    "bcc",
                    "keywords",
                    "size",
                    "receivedAt",
                    "sentAt",
                    "preview",
                    "hasAttachment",
                    "replyTo",
                    "mailboxIds",
                    "header:X-MEETING-UID:asText"
                ]
            },
            "c1"
        ]
    ]
}
```

**Comment by Arsnael** [comment]
Not sure to fully get it but would say normally yes?

**Comment by hoangdat** [comment]
We tried with `position` but the result so different when we use `position=10` and `position=20`

**Comment by Arsnael** [comment]
@hoangdat 
@vttranlina will help you on this this week :)

**Comment by dab246** [comment]
## Root cause

`Email/get` return list sorted incorrectly 

## Workaround

- Use `sortEmails` method of GetEmailResponse to sort list from response `Email/get`

**Comment by dab246** [comment]
@hieutbui  Please fix it according to the above workaround

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
