### PR TITLE
TF-3243 Fix email without content

### PR DESCRIPTION
**Pull request by dab246**
## Issue 

#3243

## Root cause

- Because the function `Uri.decodeFull(inputText)` throws an exception `FormatException: Invalid UTF-8 byte (at offset 11)` during handle `3D Links ` in DOM.
- This error only occurs on the web

## Solution

- Add `try/catch` blocks to all email `transformer` DOM handler  functions

## Resolved

- Web:

https://github.com/user-attachments/assets/de975aff-0f1d-454e-b41a-af26412e8aa8

- Mobile:

[demo-mobile.webm](https://github.com/user-attachments/assets/06d394df-f359-4271-94fa-fddaa04a436e)

### CODE REVIEW

**Comment by chibenwa** [comment]
> Add try/catch blocks to all email transformer and sanitize handler functions

Does this means that **if I send a broken base64 link** then HTML sanitizing is bypassed and thus I could pass an XSS payload *after* the broken base64 link?

**Comment by dab246** [comment]
> > Add try/catch blocks to all email transformer and sanitize handler functions
> 
> Does this means that **if I send a broken base64 link** then HTML sanitizing is bypassed and thus I could pass an XSS payload _after_ the broken base64 link?

No. We do HTML sanitization before we do URL sanitization in the a tag. So we always block XSS from the start.

**Review by tddang-linagora — DISMISSED** [review]

**Review by hoangdat — DISMISSED** [review]

**Comment by hoangdat** [comment]
please rebase @dab246

**Comment by dab246** [comment]
> please rebase @dab246

Done. @hoangdat

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
