### PR TITLE
TF-2868 Fix composer bold option toggle

### PR DESCRIPTION
**Pull request by dab246**
## Issue

#2868 

## Root cause

- Side effect of fixing memory leak error in PR https://github.com/linagora/html-editor-enhanced/pull/34. Resulting in `ToolbarWidget` not being created, causing `toolbar` object in `HtmlEditorController` to be null. And `onChangeSelection` is not listened to.

## Solution

- https://github.com/linagora/html-editor-enhanced/pull/39

## Resolved

https://github.com/linagora/tmail-flutter/assets/80730648/ab0ae98c-7081-4875-b054-c9c1dcffb856

### CODE REVIEW

**Review by tddang-linagora — COMMENTED** [review]
Should we update `toolbarType: ToolbarType.hide` in `web_editor_widget.dart` instead?

**Comment by dab246** [comment]
> Should we update `toolbarType: ToolbarType.hide` in `web_editor_widget.dart` instead?

Are not. If you do so the default toolbarwidget will be rendered. But we don't want that

**Review by tddang-linagora — APPROVED** [review]

**Comment by hoangdat** [comment]
should be move to refactor branch also

**Comment by dab246** [comment]
> should be move to refactor branch also

Done

**Comment by hoangdat** [comment]
please update to use `cnb_supported` in pubspec.

**Comment by hoangdat** [comment]
- [x] Chrome

**Comment by dab246** [comment]
> please update to use `cnb_supported` in pubspec.

Done

**Comment by hoangdat** [comment]
- [ ] test on Android: not work with `B`, `I`, ...

**Comment by dab246** [comment]
> * [ ]  test on Android: not work with `B`, `I`, ...
> * [ ]  test on iOS: @tddang-linagora

With mobile fixed at https://github.com/linagora/tmail-flutter/pull/2795

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
