### PR TITLE
Bump version to v0.14.5

### PR DESCRIPTION
**Pull request by hoangdat**
### Fixed 
- #3336 Make Echo ping of web socket optional
- #3347 Format Calendar event description
- #3341 Enable Web socket for mobile in foreground
- #3334 Remove all own resynch after any actions in mailbox, email
- #3333 Remove Mailbox/query for spam banner when reload app
- #3332 Remove resynch when switching mailbox
- #3372 Remove Mailbox resynch when Emptying trash
- #3369 Display CID without disposition as an attachment

### Added
- #3181 Contact support

### CODE REVIEW

**Comment by chibenwa** [comment]
Is it ready for me deploying it on oncommit-tmail.linagora.com ?

If so, i will do it tonight.

**Review by chibenwa — APPROVED** [review]

**Comment by hoangdat** [comment]
I still testing it, then build it. I will let you know when it is available

**Comment by tddang-linagora** [comment]
Memory usage check:
- Move emails: OK

https://github.com/user-attachments/assets/99e04261-3619-465b-8d98-733bf59d89be

- Mark emails: OK

https://github.com/user-attachments/assets/9b6944c6-0bff-4d0e-baf7-dcc1eb4589c9

**Comment by chibenwa** [comment]
As explained on the chat I am unhappy with the way it works.

We lost a loooot in user experience: the actions done by the users takes a LONG time to reflect 
(Only upon websocket notification)

If you drop the websocket connection
(eg when I did also upgrade the back...) 
Then the list not actualized

As it stands, this can't be shipped to a customer without pain.

We need to look into the Email/set RESULT

To see which emails where update it
And update the caches / view accordingly straight away
That way user actions are SYNCHRONOUS and are reflected as soon as the JMAP server answers.

Is it clear?

**Comment by chibenwa** [comment]
Empty trash is completly broken on my Linagora account

 -> It fails deleting all mails
 -> I do not have a progess bar

😑

**Pull request merged**
