### PR TITLE
TF-2857 Change new app icon

### PR DESCRIPTION
**Pull request by dab246**
## Issue

#2857 

## Resolved

- [x] Change app icon for Android

demoi

- [x] Change app icon for iOS

demo

- [x] Change app icon for Web

Screenshot 2024-05-31 at 11 59 08

- [x] Change notification icon 

- [x] Change splash screen for Android

[demo-android.webm](https://github.com/linagora/tmail-flutter/assets/80730648/1f2864fa-7fe9-4c85-a164-4bdf2c3933da)

- [x] Change splash screen for iOS

https://github.com/linagora/tmail-flutter/assets/80730648/0553b080-d866-4ed8-bd09-731565f4545a

- [x]  Change splash screen for Web

https://github.com/linagora/tmail-flutter/assets/80730648/109816f7-f9d3-4bb2-8825-47cc18810e93

### CODE REVIEW

**Comment by tddang-linagora** [comment]
App icons should be updated

- [ ] @tddang-linagora Test on Android

**Comment by tddang-linagora** [comment]
App icons should be updated

- [ ] @tddang-linagora Test on iOS

**Review by tddang-linagora — APPROVED** [review]

**Comment by dab246** [comment]
Rebase to the `refactor` is complete

**Review by tddang-linagora — APPROVED** [review]

**Comment by hoangdat** [comment]
hi @dab246 please rebase it

**Review by dab246 — COMMENTED** [review]
Approved

**Comment by hoangdat** [comment]
image

**Pull request merged**
