### PR TITLE
TF-2533 [Part-3] Replace beforeunload with pagehide

### PR DESCRIPTION
**Pull request by tddang-linagora**
### Issue
- #2533 

### Demo

**Before**

https://github.com/linagora/tmail-flutter/assets/160106668/052ab6d5-351a-430b-8837-275518c7ed3a

**After**

https://github.com/linagora/tmail-flutter/assets/160106668/72052419-c011-4b47-bc4a-de8961e34315

### CODE REVIEW

**Review by dab246 — COMMENTED** [review]
Why we need change it?. Please test on different browsers (Chrome/Safari/Firefox/Edge) to see if there is any difference?

**Comment by tddang-linagora** [comment]
> Why we need change it?. Please test on different browsers (Chrome/Safari/Firefox/Edge) to see if there is any difference?

`beforeunload` is unrealiable, and `pagehide` is perform better in the same regard that we need a way to detect unload event from js

**Comment by dab246** [comment]
> > Why we need change it?. Please test on different browsers (Chrome/Safari/Firefox/Edge) to see if there is any difference?
> 
> `beforeunload` is unrealiable, and `pagehide` is perform better in the same regard that we need a way to detect unload event from js

Is there any official documentation about this?

**Comment by tddang-linagora** [comment]
> > > Why we need change it?. Please test on different browsers (Chrome/Safari/Firefox/Edge) to see if there is any difference?
> > 
> > 
> > `beforeunload` is unrealiable, and `pagehide` is perform better in the same regard that we need a way to detect unload event from js
> 
> Is there any official documentation about this?

https://developer.chrome.com/docs/web-platform/page-lifecycle-api#the_unload_event

**Comment by dab246** [comment]
Also change it in `HtmlContentViewerOnWeb` class in email view

Screenshot 2024-04-17 at 12 13 40

**Comment by tddang-linagora** [comment]
> Also change it in `HtmlContentViewerOnWeb` class in email view
> 
> Screenshot 2024-04-17 at 12 13 40

Done

**Comment by hoangdat** [comment]
Quite good at replying big email

image

**Comment by hoangdat** [comment]
- Rare time it is still not stable, I think maybe the `pagehide` listener still not stable 
Screenshot 2024-04-25 at 16 31 20

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
