### PR TITLE
TF-797 [Web] Fix cursor position should display style of the current position in composer

### PR DESCRIPTION
**Pull request by dab246**
#797 

### Resolved

https://user-images.githubusercontent.com/80730648/183566434-666d5070-ec00-492b-97c4-260b5085a548.mov

### CODE REVIEW

**Comment by hoangdat** [comment]
How about in mobile :)

**Comment by dab246** [comment]
> How about in mobile :)

No phone related here. It belongs to 2 different controllers.

**Comment by hoangdat** [comment]
> > How about in mobile :)
> 
> No phone related here. It belongs to 2 different controllers.

please check the same for mobile

**Comment by hoangdat** [comment]
> please check the same for mobile


Ok We will do it in separated ticket

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
