### PR TITLE
TF-738 [Web] Add align button to align text in composer

### PR DESCRIPTION
**Pull request by dab246**
https://user-images.githubusercontent.com/80730648/180975046-b182fd49-beb5-4b7d-9110-e1a47a40737d.mov

### CODE REVIEW

**Comment by hoangdat** [comment]
Screen Shot 2022-07-26 at 17 02 19

@dab246 please update with new design

**Comment by dab246** [comment]
> 

It does not belong to this PR you. Don't make such stupid comments.

**Comment by dab246** [comment]
>

**Comment by dab246** [comment]
> Screen Shot 2022-07-26 at 17 02 19
> 
> @dab246 please update with new design

It does not belong to this PR you. Don't make such stupid comments.

**Comment by dab246** [comment]
> Screen Shot 2022-07-26 at 17 02 19
> 
> @dab246 please update with new design

Updated at [https://github.com/linagora/tmail-flutter/issues/759](https://github.com/linagora/tmail-flutter/issues/759)

**Review by ManhNTX — APPROVED** [review]

**Pull request merged**
