### PR TITLE
Enable GZIP for Nginx

### PR DESCRIPTION
**Pull request by quantranhong1999**
Tested and gzip works locally.
The new `nginx.conf` file = default `nginx.conf` + server block + gzip on.
The GZIP setting includes compressed mime types review is welcome.

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by chibenwa — APPROVED** [review]
Could you please use browser dev tools to show us the gains?

**Review by hoangdat — APPROVED** [review]

**Comment by hoangdat** [comment]
please let me know when it is available to merge (don't worry, our CI are off for some days)

**Comment by tanandy** [comment]
so you are only interested by gzip and not gzip_static ?

You dont have files already compressed ? and force dynamic compression in any case ? (instead of static)

**Comment by quantranhong1999** [comment]
> Could you please use browser dev tools to show us the gains?

image

- PNG zip is not useful (even add more zipped size). Maybe cause PNG is already compressed enough.
- Many font files (.ttf, .otf) do not zip (although already have that type in config, seems weird). There is a .ttf file that has been zipped (return type ttf) and other .ttf not zipped with default return type octet-stream => It looks like Nginx could have some issue recognizing .ttf files.

**Comment by quantranhong1999** [comment]
Added `application/octet-stream` and zipping works for font files now (but actually it should have worked with .ttf etc).
image

This GZIP only works for Frontend's static files. Maybe we should config GZIP for other NGINX which stays in front of James Jmap also.

**Comment by chibenwa** [comment]
> note: considers reading BREACH/CRIME attack if not done already

Clearly not an issue when serving SPA assets. No info to leak...

> so you are only interested by gzip and not gzip_static ?

That would be freaking cool if we could gzip statically, yes! A very nice to have. Quan can you have a look?

> PNG zip is not useful

Yes like on all heavily compressed files...

**Comment by quantranhong1999** [comment]
Static GZIP (all type of files) result:
image

image

**Review by Arsnael — APPROVED** [review]

**Comment by quantranhong1999** [comment]
Can we merge this?

**Comment by hoangdat** [comment]
please rebase. i will merge it

**Pull request merged**
