### PR TITLE
TF-2949 Fix remove duplicated information in email of calendar event

### PR DESCRIPTION
**Pull request by dab246**
## Issue

#2949

## Resolved

https://github.com/user-attachments/assets/3142fb15-9f4f-4162-8fe5-a8fcecd6d7ad

### CODE REVIEW

**Comment by hoangdat** [comment]
- [ ] how about for the case of many participants?

**Comment by dab246** [comment]
> * [x]  how about for the case of many participants?

Please watch the demo video from second `1:04`

Screenshot 2024-07-23 at 09 04 54

**Review by tddang-linagora — APPROVED** [review]

**Comment by hoangdat** [comment]
- [ ] how about to expand content (red square) as much as possible 
Screenshot 2024-07-26 at 15 01 39 3

**Comment by dab246** [comment]
> * [ ]  how about to expand content (red square) as much as possible
> 
> Screenshot 2024-07-26 at 15 01 39 3

We have to set its size. Currently its maximum height is `250dp`. It contains a webview so it can't auto-size to the content length because it's wrapped around a scrollview.

**Comment by hoangdat** [comment]
- [ ] we have the way to expand it but dont have the way to collapse it
image

**Comment by dab246** [comment]
> * [ ]  we have the way to expand it but dont have the way to collapse it
> 
> image

Should we do that? The design doesn't have it yet.

**Comment by hoangdat** [comment]
> We have to set its size. Currently its maximum height is 250dp. It contains a webview so it can't auto-size to the content length because it's wrapped around a scrollview.

But Mobile can show whole content. Please do the same

**Comment by dab246** [comment]
> * [x]  we have the way to expand it but dont have the way to collapse it
> 
> image

Added.

https://github.com/user-attachments/assets/e3bf36a6-ac86-41ec-997e-86c26a24a379

**Review by hoangdat — APPROVED** [review]

**Pull request merged**
