### PR TITLE
Upgrade AppAuth to v1.7.4

### PR DESCRIPTION
**Pull request by hoangdat**

### CODE REVIEW

**Comment by dab246** [comment]
why do we need this?

**Comment by hoangdat** [comment]
We upgraded appAuth in https://github.com/linagora/tmail-flutter/commit/d2fdbfab0f25647e9306ff32bc75e8c7195b3d1d

**Comment by hoangdat** [comment]
success https://github.com/linagora/tmail-flutter/actions/runs/8935881006/job/24545180504

**Review by dab246 — APPROVED** [review]
lgtm

**Pull request merged**
